var Content = [
  "the sky is blue the grass is green there are birds in the trees flowers bloom in the meadow a river flows quietly in the distance the sun sets behind the hills casting a warm glow the world is vast and full of wonders nature is a beautiful symphony of life and cycles each moment holds a unique beauty and charm it's a tapestry of existence where everything is interconnected and harmonious there's a simplicity in the rhythm of life that captivates the soul and invites contemplation a serene dance of elements unfolding in an eternal ballet",
  "in a galaxy far away there are stars and planets jedi and sith engage in epic battles the force is strong with them lightsabers clash in intense duels spaceships soar through the cosmos the death star looms threateningly rebellion fights against the empire droids beep and whirr stormtroopers march in formation the millennium falcon navigates through asteroid fields yoda imparts wisdom with a cryptic tone the dark side tempts with its power characters like luke and leia become legends the saga unfolds across trilogies creating a vast universe of imagination where the force binds everything together in an endless cosmic saga",
  "Dark Souls the acclaimed video game series known for its challenging gameplay intricate lore and unforgiving world tests players' perseverance and skill Players embark on a harrowing journey through treacherous landscapes teeming with formidable adversaries and hauntingly beautiful environments Each step forward brings encounters with grotesque creatures and monumental bosses testing the limits of one's courage and determination The narrative shrouded in enigmatic storytelling gradually unfolds through cryptic item descriptions and elusive character interactions Players navigate through desolate ruins murky swamps and towering citadels constantly facing the looming threat of death and despair",
  "the year is twenty thirty in a parallel dimension where MNNIT is rumored to be a secret training ground for intergalactic ducks yes ducks with advanced engineering degrees students are said to communicate with these feathered scholars through quacks during lectures the campus is believed to have a hidden portal to a duck-dominated universe where they exchange knowledge on quantum quacking and warp-speed waddling the college cafeteria is allegedly a front for a duck-run bakery specializing in extraterrestrial pastries conspiracy theorists claim that the dean is actually a highly intelligent duck in disguise leading a covert mission for interspecies enlightenment",
  "In a twisted alternate reality nested within the cloistered confines of MNNIT, the engineering college that once thrived with academic fervor now bears the guise of a quirky dystopia. The classrooms, once sanctuaries of enlightenment, now echo with the manic hum of cybernetic mosquitoes bred in labs gone rogue. Professors are crowned as demigods, adored for their peculiar proneness to tangents about equations no one understands. The library, a fortress of wisdom, hoards ancient scrolls filled with obsolete programming languages and paradoxical textbooks on nuclear philosophy. Students, with weary eyes, shuffle through corridors adorned with graffiti manifestos challenging the 'Internet of Things' and lamenting the loss of the 'Internet of People'",
  "engineering in india a breeding ground for innovation faces important changes stress countless exams an hefty syllabi are just a part of the fun package in a great satire engineering schools are still run by ancient methods equipping students with obsolete tech despite this theyre told theyll change the world recent stats reveal high numbers of engineers few jobs rumors hint at subjects like how to selfdestruct brigade machines in the new syllabus",
];

var parcedCont = [];
for (var i = 0; i < Content.length; i++) {
  parcedCont.push(Content[i].split(" "));
}

export default Content;
export { parcedCont };
